import { HeaderList } from "../header/Header";

export enum axiosType {
  get = "get",
  post = "post",
  put = "put",
  delete = "delete",
}
// 8193043551
export const exploreDescription =
  "Explore stunning destinations, from exotic tropical paradises to historic landmarks and vibrant cityscapes with Lyamii.";

export const mapDescription =
  "It is an invitation to expand the horizons of your existence and witness the remarkable resilience of human spirit. Through travel, we become citizens of the FaWordpressSimple, the best version of ourselves.";

export const reasons = [
  {
    title: "Global Reach",
    img: require("../../../Assets/globe.png"),
    description:
      "Our global accommodation covers 77+ countries. 500+ volunteers are always there to assist you on the way. Find comfort wherever you wander.",
  },
  {
    title: "Complete Tours",
    img: require("../../../Assets/tick1.png"),
    description:
      "The traveller ID solves all your headaches. Travel Insurance? Sorted. Air Tickets? Done. Government Documentation? Checked. All stays? Covered. Pack your bag and leave the rest to us.",
  },
  {
    title: "Secure & Convenient",
    img: require("../../../Assets/fingerprint1.png"),
    description:
      "Experience secure and seamless transactions. Enjoy convenience and peace of mind with our online/offline payment model. Embrace effortless currency exchange in our Journey of a Lifetime tours.",
  },
  {
    title: "Has something for Everyone",
    img: require("../../../Assets/giftbox.png"),
    description:
      "Lyamii presents vacations for everyone, to everywhere. Do not hesitate to dive into the exploration of yourself. Scroll through snow, ocean, wildlife, alleys and select your journey. You have us to handle the rest.",
  },
];

export const reviews = [
  {
    name: "Sarah M",
    review:
      "I had an amazing experience booking my vacation through this website. The user-friendly interface made it super easy to browse through various destinations and find the perfect package for my family. The customer support team was incredibly helpful in answering all my questions and providing recommendations. Our trip went off without a hitch, and I can't wait to use this website again for my next adventure!",
  },
  {
    name: "John D",
    review:
      "Overall, a great travel booking website! I found some fantastic deals and discounts on flights and hotels for my recent solo trip. The search filters were handy for narrowing down my options, and the booking process was smooth. The only reason I'm not giving it 5 stars is that I encountered a minor issue with my hotel reservation, but the customer support team promptly resolved it. I'd definitely use this website again for my next getaway.",
  },
  {
    name: "Lisa T",
    review:
      "This website has a wide range of travel options, but my experience was a bit mixed. I found a great deal on a tour package to a beautiful destination, but the booking process felt a bit clunky, and I had some trouble with payment processing. Eventually, I managed to secure my reservation with the help of customer support, but it was a bit frustrating. On the positive side, the tour itself was fantastic, and the local guides were knowledgeable and friendly.",
  },
];

export const communities: HeaderList[] = [
  { name: "About us", path: "/about" },
  { name: "Our Mission", path: "/mission" },
  { name: "Join us", path: "/joinus" },
  { name: "Reviews", path: "/reviews" },
  { name: "Privacy policy", path: "/privacypolicy" },
  { name: "Terms and conditions", path: "/termconditions" },
  { name: "FAQ", path: "/" },
];
export const supports: HeaderList[] = [
  { name: "My Profile", path: "/profile" },
  { name: "Helpdesk", path: "/helpdesk" },
  { name: "Feedback", path: "/feedback" },
];

export const journeyOptions = [
  {
    name: "ROYAL BHARAT EDITION",
    path: require("../../../Assets/bharat.png"),
  },
  {
    name: "BACKPACKERS EDITION",
    path: require("../../../Assets/backpackers.jpeg"),
  },
  {
    name: "COMBOS",
    path: require("../../../Assets/combo.jpeg"),
  },
];

export const internationalTours = [
  {
    from: "IND",
    to: "ITALY",
    path: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
  },
  {
    from: "IND",
    to: "FRANCE",
    path: "https://cdn.pixabay.com/photo/2014/11/13/23/34/palace-530055_12jpg",
  },
  {
    from: "IND",
    to: "GERMANY",
    path: "https://cdn.pixabay.com/photo/2015/03/31/23/08/neuschwanstein-701732_12jpg",
  },
  {
    from: "IND",
    to: "SWITZERLAND",
    path: "https://cdn.pixabay.com/photo/2016/08/22/10/20/city-1611657_12jpg",
  },
];

export const bharatTours = [
  {
    from: "kolkatal",
    to: "delhi",
    days: "15",
    priceInUSD: "12,000 USD",
    priceInEUR: "11,500 EUR",
    priceInAED: "45,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Kolkatal",
      "Kolkata",
      "Hyderabad",
      "Hyderabad",
      "Kerala Backwaters",
      "Kerala Backwaters",
      "Mumbai",
      "Mumbai",
      "Udaipur",
      "Jodhpur",
      "Jodhpur",
      "Jaipur",
      "Jaipur",
      "Lucknow",
      "Agra",
      "Delhi",
      "Delhi",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    days: "20",
    priceInUSD: "15,000 USD",
    priceInEUR: "14,500 EUR",
    priceInAED: "55,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Kolkata",
      "Andaman Nicobar",
      "Andaman Nicobar",
      "Kolkata",
      "Varanasi",
      "Varanasi",
      "Hyderabad",
      "Hyderabad",
      "Kerala Backwaters",
      "Kerala Backwaters",
      "Mumbai",
      "Mumbai",
      "Vadodara",
      "Statue of Unity",
      "Jaipur",
      "Jaipur",
      "Bharatpur",
      "Agra",
      "Delhi",
      "Kashmir",
      "Kashmir",
      "Kashmir",
      "Delhi",
      "Delhi",
    ],
  },
  {
    from: "kolkatal",
    to: "delhi",
    days: "30",
    priceInUSD: "18,000 USD",
    priceInEUR: "16,000 EUR",
    priceInAED: "65,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Kolkata",
      "Andaman Nicobar",
      "Andaman Nicobar",
      "Andaman Nicobar",
      "Kolkata",
      "Varanasi",
      "Varanasi",
      "Varanasi",
      "Hyderabad",
      "Hyderabad",
      "Kerala Backwaters",
      "Kerala Backwaters",
      "Mumbai",
      "Mumbai",
      "Vadodara",
      "Statue of Unity",
      "Jaipur",
      "Jaipur",
      "Jaipur",
      "Delhi",
      "Agra",
      "Kashmir",
      "Kashmir",
      "Kashmir",
      "Leh",
      "Nubra Valley",
      "Nubra Valley",
      "Pangong Lake",
      "Leh",
      "Amritsar",
      "Amritsar",
      "Amritsar",
      "Delhi",
      "Delhi",
    ],
  },
  {
    from: "kolkatal",
    to: "delhi",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Kolkata",
      "Kolkata",
      "Sundarbans",
      "Sundarbans",
      "Kolkata",
      "Andaman Nicobar",
      "Andaman Nicobar",
      "Andaman Nicobar",
      "Kolkata-Shillong",
      "Meghalaya",
      "Meghalaya",
      "Delhi",
      "Agra",
      "Lucknow",
      "Varanasi",
      "Varanasi",
      "Delhi",
      "Sreenagar",
      "Sreenagar",
      "Pahalgam",
      "Sonamarg",
      "Sonamarg",
      "Leh",
      "Leh",
      "Nubra Valley",
      "Pangong- Leh",
      "Chandigarh",
      "Chandigarh",
      "Patiala",
      "Delhi",
      "Bikaner",
      "Bikaner",
      "Jaisalmer",
      "Jodhpur",
      "Udaipur",
      "Jaipur",
      "Jaipur",
      "VadJodhpurodara",
      "Vadodara",
      "Mumbai",
      "Mumbai",
      "Mumbai - Hyderabad",
      "Hyderabad",
      "Cochin",
      "Varkala/Mararikulam",
      "Kanyakumari",
      "Alleppey",
      "TN- Traditional Stay ",
      "TN- Traditional Stay ",
      "Bengaluru",
      "Bengaluru",
    ],
  },
];
export const backpackersTours = [
  {
    from: "kolkatal",
    to: "Bengaluru",
    days: "20",
    tourType: "Vagabond's Wishlist",
    priceInUSD: "1,70,000 USD",
    priceInEUR: "1,50,000 EUR",
    priceInAED: "",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Kolkata",
      "Kolkata",
      "Sundarbans",
      "Sundarbans",
      "Kolkata",
      "Shillong",
      "Meghalaya",
      "Delhi",
      "Agra",
      "Lucknow",
      "Varanasi",
      "Varanasi",
      "Delhi",
      "Amritsar",
      "Amritsar",
      "Jaipur",
      "Jaipur",
      "Udaipur",
      "Mumbai",
      "Mumbai",
      "Goa",
      "Goa",
      "Humpi",
      "Hyderabad",
      "Hyderabad",
      "Kerala",
      "Kerala",
      "TN- Traditional Stay ",
      "TN- Traditional Stay ",
      "Mysore",
      "Bengaluru",
      "Bengaluru",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    days: "50",
    priceInUSD: "5,20,000 USD",
    priceInEUR: "",
    tourType: "Vagabond's Wishlist",
    priceInAED: "",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Kolkata",
      "Kolkata",
      "Sundarbans",
      "Sundarbans",
      "Kolkata",
      "Kolkata",
      "Shillong",
      "Meghalaya",
      "Meghalaya-Kolkata",
      "Andaman Nicobar",
      "Andaman Nicobar",
      "Andaman Nicobar",
      "Chennai",
      "TN",
      "TN",
      "TN",
      "Kerala",
      "Kerala",
      "Cochin",
      "Mysore",
      "Bengaluru",
      "Bengaluru",
      "Goa",
      "Goa",
      "Goa",
      "Mumbai",
      "Mumbai",
      "Mumbai",
      "Udaipur",
      "Udaipur",
      "Pushkar",
      "Jaipur",
      "Jaipur",
      "Amritsar",
      "Amritsar",
      "Delhi",
      "Agra",
      "Lucknow",
      "Lucknow",
      "Varanasi",
      "Varanasi",
      "Varanasi",
      "Delhi",
      "Delhi",
      "Srinagar",
      "Srinagar",
      "Kashmir",
      "Kashmir",
      "Kashmir",
      "Leh",
      "Leh",
      "Nubra Valley",
      "Leh-Manali",
      "Manali",
      "Kasol",
      "Kasol",
      "Shimla",
      "Shimla",
      "Chandigarh",
      "Chandigarh",
      "Haridwar",
      "Rishikesh",
      "Rishikesh",
      "Delhi",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Vagabond's Wishlist",
    days: "75",
    priceInUSD: "18,000 USD",
    priceInEUR: "16,000 EUR",
    priceInAED: "65,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Delhi",
      "Delhi",
      "Delhi",
      "Jaipur",
      "Udaipur",
      "Jaisalmer",
      "Bikaner",
      "Ajmer",
      "Gujrat",
      "Gujrat",
      "Gujrat",
      "Gujrat",
      "MP",
      "MP",
      "Maharashtra",
      "Maharashtra",
      "Maharashtra",
      "Maharashtra",
      "Goa",
      "Goa",
      "Goa",
      "Karnataka",
      "Karnataka",
      "Karnataka",
      "Karnataka",
      "Tamilnadu",
      "Tamilnadu",
      "Tamilnadu",
      "Tamilnadu",
      "Tamilnadu",
      "Kerala",
      "Kerala",
      "Kerala",
      "Kerala",
      "Hyderabad",
      "Hyderabad",
      "Kolkata",
      "Kolkata",
      "Andaman",
      "Andaman",
      "Andaman",
      "Kolkata",
      "Sundarbans",
      "Sundarbans",
      "Sundarbans",
      "North East",
      "North East",
      "North East",
      "North East",
      "North East",
      "North East",
      "North East",
      "Sikkim",
      "Sikkim",
      "Bihar",
      "Bihar",
      "Uttar Pradesh",
      "Uttar Pradesh",
      "Uttar Pradesh",
      "Uttar Pradesh",
      "Uttar Pradesh",
      "Jammu Kashmir",
      "Jammu Kashmir",
      "Ladakh",
      "Ladakh",
      "Ladakh",
      "Ladakh",
      "Ladakh",
      "Himachal",
      "Himachal",
      "Himachal",
      "Himachal",
      "Chandigarh",
      "Chandigarh",
      "Punjab",
      "Punjab",
      "Haryana",
      "Uttarakhand",
      "Uttarakhand",
      "Uttarakhand",
      "Uttarakhand",
      "Delhi",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Spiritual Enlightenment",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Auroville",
      "Pondicherry",
      "Rishikesh",
      "Haridwar",
      "Lucknow",
      "Varanasi",
      "Pushkar",
      "Ajmer",
      "Mathura",
      "Vrindavan",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Spiritual Enlightenment",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Auroville",
      "Pondicherry",
      "Rishikesh",
      "Haridwar",
      "Lucknow",
      "Varanasi",
      "Pushkar",
      "Ajmer",
      "Mathura",
      "Vrindavan",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Spiritual Enlightenment",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Auroville",
      "Pondicherry",
      "Rishikesh",
      "Haridwar",
      "Lucknow",
      "Varanasi",
      "Pushkar",
      "Ajmer",
      "Mathura",
      "Vrindavan",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Spiritual Enlightenment",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Auroville",
      "Pondicherry",
      "Rishikesh",
      "Haridwar",
      "Lucknow",
      "Varanasi",
      "Pushkar",
      "Ajmer",
      "Mathura",
      "Vrindavan",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Colours of Festivals",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Ganga Dussehra",
      "Hornbill Festival",
      "Onam",
      "Durga Puja",
      "Diwali",
      "Holi",
      "Theyyam",
      "Garba- Navaratri",
      "Losar",
      "Dasara",
      "Ganesh Chaturthi",
      "Janmashtami",
      "Eid-ul-Fitr",
      "Christmas",
      "Baisakhi",
      "Buddha Purnima",
      "Pongal",
      "Bihu",
      "Makar Sankranti",
      "Hemis",
      "Saga Dawa",
      "Mahavir Jayanti",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Wild Encounter",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Tigers",
      "The Royal Bengal Tiger",
      "Maharajas of Maharashtra",
      "Jim Corbett",
      "Roars of Ranthambore",
      "Gir NP Madhya Pradesh Majestics",
      "Asiatic Lions",
      "Gir National Park",
      "Ranthambore",
      "Elephant Kerala",
      "Snow Leopards Spiti Valley",
      "Red Panda",
      "Singalila National Park",
      "Fishing Cat West Bengal",
      "Birds",
      "Butterflies",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Sandy Escape",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Mumbai",
      "Mumbai",
      "Goa",
      "Goa",
      "Goa",
      "Kerala",

      "Kerala",
      "Lakshadweep",
      "Lakshadweep",
      "Lakshadweep",
      "Kerala",
      "Kerala",
      "Tamilnadu",
      "Tamilnadu",
      "Tamilnadu",
      "Tamilnadu",
      "Andhra",
      "Andhra",
      "Odisha",
      "Odisha",
      "Odisha",
      "West Bengal",
      "West Bengal",
      "Andaman",
      "Andaman",
      "Andaman",
      "Andaman",
      "Kolkata",
      "Mumbai",
      "Mumbai",
    ],
  },
  {
    from: "kolkata",
    to: "delhi",
    tourType: "Seven Sisters",
    days: "50",
    priceInUSD: "22,000 USD",
    priceInEUR: "20,500 EUR",
    priceInAED: "80,000 AED",
    img: "https://cdn.pixabay.com/photo/2016/04/15/13/30/fassa-valley-1331004_12jpg",
    places: [
      "Guwahati",
      "Tawang",
      "Tawang",
      "Bomdila",
      "Kaziranga NP",
      "Kaziranga",
      "Shivasagar",
      "Mon town",
      "Mon town",
      "Dzukou Valley",
      "Dzukou Valley",
      "Kohima",
      "Imphal",
      "Loktak Lake",
      "Agartala",
      "Agartala",
      "Aizawl",
      "Aizawl",
      "Shillong",
      "Shillong",
      "Shillong",
      "Guwahati",
      "Guwahati",
      "Guwahati",
    ],
  },
];
//   3. 'COMBOS'
//   1.1. South Indian Combo
//   (Kerala, Karnataka, Tamil Nadu) + Pondicherry
//   Karnataka
//   'Bengaluru
//   'Mysore 'Coorg 'Hampi 'Badami

//    'Kabini
//   'Jog falls
//   'Mangalore
//   'Karwar
//   'Gokarna
//   'Udupi
//   'Murudeshwar
//   'Kudremukh
//   Kerala
//   'Kochi
//   'Munnar
//   'Alappuzha
//   'Thiruvananthapuram
//   'Wayanad
//   'Kovalam
//   'Kozhikode
//   'Periyar National Park
//   'Kumarakom
//   'Varkala
//   'Eravikulam National Park
//   'Kollam
//   'Thrissur
//   'Palakkad
//   'Idukki
//   'Marari Beach ●
//   2. The Ganga.
//   (WB, Bihar, UP, UK)
//   3. The North Combo.
//   (Uttarakhand, Himachal, Leh, Kashmir)

//   4. West Coast Combo.
//   (Kerala, Goa, Maharashtra, Gujrat)
// ];
export const filterList = [
  {
    filterName: "Type",
    subFilter: [
      { checked: false, label: "Deluxe" },
      { checked: false, label: "Backpacker" },
      { checked: false, label: "Standard" },
      { checked: false, label: "Indian Passport Holders" },
      { checked: false, label: "India Tours" },
    ],
  },
  {
    filterName: "Continents",
    subFilter: [
      { checked: false, label: "Asia" },
      { checked: false, label: " Africa" },
      { checked: false, label: " North America" },
      { checked: false, label: " South America" },
      { checked: false, label: " Antarctica" },
      { checked: false, label: " Europe" },
      { checked: false, label: " Australia" },
    ],
  },
  {
    filterName: "Days",
    subFilter: [
      {
        checked: false,
        label: "less than 5",
      },
      {
        checked: false,
        label: "5 - 15",
      },
      {
        checked: false,
        label: "15-25",
      },
      {
        checked: false,
        label: "25-45",
      },
      {
        checked: false,
        label: "45-75",
      },
      {
        checked: false,
        label: "more than 75",
      },
    ],
  },
  {
    filterName: "Price Range",
    subFilter: [
      { checked: false, label: "less than 2000" },
      { checked: false, label: "2000 - 5000" },
      { checked: false, label: "5000 - 10000" },
      { checked: false, label: "10000 - 25000" },
      { checked: false, label: "more than 25000" },
    ],
  },
]