export const escapeRoute = [
  { stage: "Sign in", flag: false },
  { stage: "Profile Update", flag: false },
  { stage: "Verification", flag: false },
  { stage: "Travellers ID", flag: false },
  { stage: "Book Now", flag: false },
  { stage: "Documentation", flag: false },
  { stage: "Tour ID", flag: false },
  { stage: "Arrival", flag: false },
  { stage: "Ongoing Tour ", flag: false },
  { stage: "Completed Tour: 1", flag: false },
  { stage: "Souvenirs", flag: false },
  { stage: "Journal ", flag: false },
  { stage: "New Tour ID", flag: false },
  { stage: "Arrival", flag: false },
  { stage: "Ongoing Tour ", flag: false },
  { stage: "Completed Tour: 2", flag: false },
  { stage: "Souvenirs", flag: false },
  { stage: "Journal", flag: false },
];
