export const tours = [
  {
    packageId: "RIE07",
    packageName: "The Eastern India",
    title: "Enlighenment of Eastern India",
    flagCode: "IN",
    description:
      "Welcome to Kolk Immerse Yourself Indulge Your Senses Engage With The Kolkata's Warmth",
    overview: "Overview East India",
    highlights: [
      "Experience the Visite the largest Spend a morning Journey to the South Feel the charm of Enjoy Indian cuisines",
    ],
    noOfDays: 7,
    itinerary: {
      Day1: "City of Joy Jet Lag Leisure Evening Cultural",
      Day2: "Kolkata: Princep Ghat Victoria Memorial Coffee House Kumortuli",
      Day3: "Kolkata-Shillong: Mullick Ghat Flow Howrah Bridge Airport Drop and Pickup",
      Day4: "Meghalaya: Dawki River Living Root Polo Bazaar",
      Day5: "Meghalaya: Elephant Falls Mawlynnong Village",
      Day6: "Mawlynnog village: Sky View Point Borhil Falls Airport Drop and Pickup",
      Day7: "Kolkata: Belur Math Dakshineswar Temple Rooftop Concert",
    },
    includes: [
      "Domestic Flights",
      "Lounge Access",
      "Airport drop-pickup",
      "Currency Exchange ",
      "Travel Insurance",
      "Health Insurance",
      "UPI Wallet",
      "Luxury Accommodations",
      "Cuisines",
      "SUV Transfers",
      "Personal Guide",
      "Entry Tickets ",
      "Show Tickets",
      "Activities",
      "Round the Clock",
    ],
    destinations: ["Kolkata", "Shillong", "Meghalaya", "Mawlynnong"],
    packagePrice: [
      "1,530 KWD",
      "1,880 BHD",
      "4,000 GBP",
      "4,400 CHF",
      "4,500 EUR",
      "5,000 USD",
      "7,600 AUD",
      "18,200 AED",
    ],
    rating: 5,
    currencyLabel: "INR",
    tripType: "BACKPACKER",
    country: "India",
    imageUri: [
      "15g5EvDhBSNxSSEgZ_sryNZhqic0EB5lm",
      "15g5EvDhBSNxSSEgZ_sryNZhqic0EB5lm",
    ],
  },
  {
    packageId: "RIE07",
    packageName: "The Eastern India",
    title: "Enlighenment of Eastern India",
    flagCode: "IN",
    description:
      "Welcome to Kolk Immerse Yourself Indulge Your Senses Engage With The Kolkata's Warmth",
    overview: "Overview East India",
    highlights: [
      "Experience the Visite the largest Spend a morning Journey to the South Feel the charm of Enjoy Indian cuisines",
    ],
    noOfDays: 7,
    itinerary: {
      Day1: ["City of Joy Jet Lag Leisure Evening Cultural"],
      Day2: ["Kolkata: Princep Ghat Victoria Memorial Coffee House Kumortuli"],
      Day3: [
        "Kolkata-Shillong: Mullick Ghat Flow Howrah Bridge Airport Drop and Pickup",
      ],
      Day4: ["Meghalaya: Dawki River Living Root Polo Bazaar"],
      Day5: ["Meghalaya: Elephant Falls Mawlynnong Village"],
      Day6: [
        "Mawlynnog village: Sky View Point Borhil Falls Airport Drop and Pickup",
      ],
      Day7: ["Kolkata: Belur Math Dakshineswar Temple Rooftop Concert"],
    },
    includes: [
      "Domestic Flights",
      "Lounge Access",
      "Airport drop-pickup",
      "Currency Exchange ",
      "Travel Insurance",
      "Health Insurance",
      "UPI Wallet",
      "Luxury Accommodations",
      "Cuisines",
      "SUV Transfers",
      "Personal Guide",
      "Entry Tickets ",
      "Show Tickets",
      "Activities",
      "Round the Clock",
    ],
    destinations: ["Kolkata", "Shillong", "Meghalaya", "Mawlynnong"],
    packagePrice: [
      "1,530 KWD",
      "1,880 BHD",
      "4,000 GBP",
      "4,400 CHF",
      "4,500 EUR",
      "5,000 USD",
      "7,600 AUD",
      "18,200 AED",
    ],
    rating: 5,
    currencyLabel: "INR",
    tripType: "BACKPACKER",
    country: "India",
    imageUri: [
      "15g5EvDhBSNxSSEgZ_sryNZhqic0EB5lm",
      "15g5EvDhBSNxSSEgZ_sryNZhqic0EB5lm",
    ],
  },
  {
    packageId: "RIE07",
    packageName: "The Eastern India",
    title: "Enlighenment of Eastern India",
    flagCode: "IN",
    description:
      "Welcome to Kolk Immerse Yourself Indulge Your Senses Engage With The Kolkata's Warmth",
    overview: "Overview East India",
    highlights: [
      "Experience the Visite the largest Spend a morning Journey to the South Feel the charm of Enjoy Indian cuisines",
    ],
    noOfDays: 7,
    itinerary: {
      Day1: "City of Joy Jet Lag Leisure Evening Cultural",
      Day2: "Kolkata: Princep Ghat Victoria Memorial Coffee House Kumortuli",
      Day3: "Kolkata-Shillong: Mullick Ghat Flow Howrah Bridge Airport Drop and Pickup",
      Day4: "Meghalaya: Dawki River Living Root Polo Bazaar",
      Day5: "Meghalaya: Elephant Falls Mawlynnong Village",
      Day6: "Mawlynnog village: Sky View Point Borhil Falls Airport Drop and Pickup",
      Day7: "Kolkata: Belur Math Dakshineswar Temple Rooftop Concert",
    },
    includes: [
      "Domestic Flights",
      "Lounge Access",
      "Airport drop-pickup",
      "Currency Exchange ",
      "Travel Insurance",
      "Health Insurance",
      "UPI Wallet",
      "Luxury Accommodations",
      "Cuisines",
      "SUV Transfers",
      "Personal Guide",
      "Entry Tickets ",
      "Show Tickets",
      "Activities",
      "Round the Clock",
    ],
    destinations: ["Kolkata", "Shillong", "Meghalaya", "Mawlynnong"],
    packagePrice: [
      "1,530 KWD",
      "1,880 BHD",
      "4,000 GBP",
      "4,400 CHF",
      "4,500 EUR",
      "5,000 USD",
      "7,600 AUD",
      "18,200 AED",
    ],
    rating: 5,
    currencyLabel: "INR",
    tripType: "BACKPACKER",
    country: "India",
    imageUri: [
      "15g5EvDhBSNxSSEgZ_sryNZhqic0EB5lm",
      "15g5EvDhBSNxSSEgZ_sryNZhqic0EB5lm",
    ],
  },
];
